# NumPy Exercises — 50 Problems

**Instructions:**
- Run the first cell to import NumPy before starting.
- Each exercise has a **Question** and an **Input** (where given).
- Write your solution in the `# Write your code here:` cell below each question.
- Run your cell to check your output.
- Do **not** modify the Input cells or the import cell.

> **Tip:** Use `Shift + Enter` to run a cell and move to the next one.

## Setup

In [26]:
# Run this cell before starting — do not modify
import numpy as np

## Section 1 — Array Basics (Exercises 1–10)

### Exercise 1 — NumPy Version

**Question:** Print the version of NumPy.


In [27]:
import numpy as np
print(np.__version__)

2.0.2


### Exercise 2 — 1D Array

**Question:** Create a 1D array of numbers from 0 to 9.


In [28]:
array = [0,1,2,3,4,5,6,7,8,9]


### Exercise 3 — Boolean Array

**Question:** Create a 3×3 NumPy array of all `True`s.


In [29]:
import numpy as np
array = np.full((3,3),True)
print(array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### Exercise 4 — Filter Odd Numbers

**Question:** Extract all odd numbers from `arr`.


In [30]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd = arr[arr % 2 != 0]
print(odd)

[1 3 5 7 9]


### Exercise 5 — Replace In-Place

**Question:** Replace all odd numbers in `arr` with `-1`.


In [32]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
# Write your code here:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 != 0] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### Exercise 6 — Replace Without Modifying Original

**Question:** Replace all odd numbers in `arr` with `-1` **without** changing the original array.


In [34]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
# Write your code here:
import numpy as np
arr = np.array([0,1,2,3,4,5,6,7,8,9])
new_arr = arr.copy()
new_arr[new_arr % 2 != 0] =-1
print(new_arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### Exercise 7 — Reshape Array

**Question:** Convert a 1D array to a 2D array with 2 rows.


In [36]:
# Input — do not modify
arr = np.arange(10)

In [37]:
# Write your code here:
import numpy as np
arr = np.arange(10)
new_arr = arr.reshape(2, 5)

print(new_arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


### Exercise 8 — Vertical Stack

**Question:** Stack arrays `a` and `b` vertically.


In [38]:
# Input — do not modify
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [39]:
# Write your code here:
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### Exercise 9 — Horizontal Stack

**Question:** Stack arrays `a` and `b` horizontally.


In [40]:
# Input — do not modify
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [41]:
# Write your code here:
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### Exercise 10 — Custom Sequence

**Question:** Create the following pattern **without hardcoding**. Use only NumPy functions and the input array `a`.

Expected output: `array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])`


In [42]:
# Input — do not modify
a = np.array([1, 2, 3])

In [43]:
# Write your code here:
import numpy as np

a = np.array([1, 2, 3])

result = np.hstack([np.repeat(a, 3),
                    np.tile(a, 3)])

print(result)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


## Section 2 — Set Operations & Filtering (Exercises 11–19)

### Exercise 11 — Common Items

**Question:** Get the common items between arrays `a` and `b`.


In [44]:
# Input — do not modify
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [45]:
# Write your code here:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


### Exercise 12 — Remove Items

**Question:** From array `a`, remove all items present in array `b`.


In [46]:
# Input — do not modify
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [47]:
# Write your code here:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(np.setdiff1d(a,b))

[1 2 3 4]


### Exercise 13 — Matching Positions

**Question:** Get the positions where elements of `a` and `b` match.


In [48]:
# Input — do not modify
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [49]:
# Write your code here:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(a==b))

(array([1, 3, 5, 7]),)


### Exercise 14 — Extract Range

**Question:** Get all items between 5 and 10 from array `a`.


In [50]:
# Input — do not modify
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [51]:
# Write your code here:
import numpy as np
a = np.array([2, 6, 1, 9, 10, 3, 27])
print(a[(a<=10) & (a>=5)])

[ 6  9 10]


### Exercise 15 — Vectorize a Function

**Question:** Convert the scalar function `maxx` below to work on two arrays.


In [52]:
# Input — do not modify
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

In [53]:
# Write your code here:
import numpy as np
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max = np.vectorize(maxx)

print(pair_max(a, b))

[6 7 9 8 9 7 5]


### Exercise 16 — Swap Columns

**Question:** Swap columns 1 and 2 in array `arr`.


In [54]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [55]:
# Write your code here:
import numpy as np
arr = np.arange(9).reshape(3,3)

arr[:, [0, 1]] = arr[:, [1, 0]]

print(arr)


[[1 0 2]
 [4 3 5]
 [7 6 8]]


### Exercise 17 — Swap Rows

**Question:** Swap rows 1 and 2 in array `arr`.


In [56]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [57]:
# Write your code here:
import numpy as np
arr = np.arange(9).reshape(3,3)
arr[[0,1],:]= arr[[1,0],:]
print(arr)

[[3 4 5]
 [0 1 2]
 [6 7 8]]


### Exercise 18 — Reverse Rows

**Question:** Reverse the rows of the 2D array `arr`.


In [58]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [59]:
# Write your code here:
import numpy as np
arr = np.arange(9).reshape(3,3)
arr[:,:]=arr[::-1,:]
print(arr)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


### Exercise 19 — Reverse Columns

**Question:** Reverse the columns of the 2D array `arr`.


In [60]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [61]:
# Write your code here:
import numpy as np
arr = np.arange(9).reshape(3,3)
arr = arr[:,::-1]
print(arr)

[[2 1 0]
 [5 4 3]
 [8 7 6]]


## Section 3 — Printing & Formatting (Exercises 20–24)

### Exercise 20 — Random Float Array

**Question:** Create a 2D array of shape 5×3 containing random decimal numbers between 5 and 10.


In [62]:
# Write your code here:
import numpy as np
arr = np.random.uniform(5,10,size =(5,3))
print(arr)

[[7.15852092 9.7001491  9.08824689]
 [6.68055975 5.87705227 6.86416023]
 [5.02844254 6.26213177 8.97831254]
 [5.07627486 7.99421688 8.0190227 ]
 [5.52573843 6.90971722 5.18238028]]


### Exercise 21 — Decimal Places

**Question:** Print only 3 decimal places of the array `rand_arr`.


In [63]:
# Input — do not modify
rand_arr = np.random.random((5,3))

In [64]:
# Write your code here:
import numpy as np
rand_arr = np.random.random((5,3))

print(np.round(rand_arr,3))


[[0.975 0.885 0.36 ]
 [0.599 0.355 0.34 ]
 [0.178 0.238 0.045]
 [0.505 0.376 0.593]
 [0.63  0.143 0.934]]


### Exercise 22 — Suppress Scientific Notation

**Question:** Pretty print `rand_arr` by suppressing scientific notation (like `1e10`).


In [65]:
# Input — do not modify
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3

In [66]:
# Write your code here:
import numpy as np
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=True)

print(rand_arr)

[[0.0005434  0.00027837 0.00042452]
 [0.00084478 0.00000472 0.00012157]
 [0.00067075 0.00082585 0.00013671]]


### Exercise 23 — Limit Print Output

**Question:** Limit the number of items printed in array `a` to a maximum of 6 elements.


In [67]:
# Input — do not modify
a = np.arange(15)

In [68]:
# Write your code here:
import numpy as np
a = np.arange(15)
np.set_printoptions(threshold=6)

print(a)

[ 0  1  2 ... 12 13 14]


### Exercise 24 — Print Full Array

**Question:** Print the full NumPy array `a` without truncating.


In [69]:
# Input — do not modify
np.set_printoptions(threshold=6)
a = np.arange(15)

In [70]:
# Write your code here:
import numpy as np
np.set_printoptions(threshold=6)
a = np.arange(15)
np.set_printoptions(threshold=np.inf)

print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Section 4 — Iris Dataset (Exercises 25–46)

### Exercise 25 — Import Dataset

**Question:** Import the Iris dataset keeping the text intact.

> URL: `https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv`


In [71]:
# Write your code here:
import pandas as pd

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv"

df = pd.read_csv(url, header=None)

print(df.head())

     0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa


### Exercise 26 — Extract Text Column

**Question:** Extract the text column `species` from the 1D iris dataset imported in Exercise 25.

*# Make sure you have run Exercise 25 first so that iris_data is defined.*


In [72]:
# Write your code here:
import pandas as pd

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv"

df = pd.read_csv(url, header=None)

species = df[4]

print(species)

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: 4, Length: 150, dtype: object


### Exercise 27 — 1D to 2D Array

**Question:** Convert the 1D iris dataset to a 2D array `iris_2d` by omitting the species text field.

*# Make sure you have run Exercise 25 first.*


In [73]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv"

iris_data = pd.read_csv(url, header=None)

iris_2d = iris_data.iloc[:, :4].to_numpy()

print(iris_2d)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

### Exercise 28 — Mean, Median, Std

**Question:** Find the mean, median, and standard deviation of the sepal length (1st column) of `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [74]:
# Write your code here:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv"

iris_data = pd.read_csv(url, header=None)


iris_2d = iris_data.iloc[:, :4].to_numpy()


sepal_length = iris_2d[:, 0]

mean = np.mean(sepal_length)
median = np.median(sepal_length)
std = np.std(sepal_length)

# Print results
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std)

Mean: 5.843333333333334
Median: 5.8
Standard Deviation: 0.8253012917851409


### Exercise 29 — Normalize Array

**Question:** Create a normalized form of iris's sepal length whose values range exactly between 0 and 1 (minimum → 0, maximum → 1).

*# Make sure you have run Exercise 27 first.*


In [75]:
# Write your code here:
import pandas as pd
import numpy as np


url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv"

iris_data = pd.read_csv(url, header=None)

iris_2d = iris_data.iloc[:, :4].to_numpy()


sepal_length = iris_2d[:, 0]


normalized = (sepal_length - np.min(sepal_length)) / (np.max(sepal_length) - np.min(sepal_length))

print(normalized)

[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667 0.30555556 0.13888889
 0.13888889 0.         0.41666667 0.38888889 0.30555556 0.22222222
 0.38888889 0.22222222 0.30555556 0.22222222 0.08333333 0.22222222
 0.13888889 0.19444444 0.19444444 0.25       0.25       0.11111111
 0.13888889 0.30555556 0.25       0.33333333 0.16666667 0.19444444
 0.33333333 0.16666667 0.02777778 0.22222222 0.19444444 0.05555556
 0.02777778 0.19444444 0.22222222 0.13888889 0.22222222 0.08333333
 0.27777778 0.19444444 0.75       0.58333333 0.72222222 0.33333333
 0.61111111 0.38888889 0.55555556 0.16666667 0.63888889 0.25
 0.19444444 0.44444444 0.47222222 0.5        0.36111111 0.66666667
 0.36111111 0.41666667 0.52777778 0.36111111 0.44444444 0.5
 0.55555556 0.5        0.58333333 0.63888889 0.69444444 0.66666667
 0.47222222 0.38888889 0.33333333 0.33333333 0.41666667 0.47222222
 0.30555556 0.47222222 0.66666667 0.55555556 0.36111111 0.33333333
 0.33333

### Exercise 30 — Softmax Score

**Question:** Compute the softmax score of the sepal length column.

*# Make sure you have run Exercise 27 first.*


In [76]:
# Write your code here:
import pandas as pd
import numpy as np


url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv"

iris_data = pd.read_csv(url, header=None)

iris_2d = iris_data.iloc[:, :4].to_numpy()


sepal_length = iris_2d[:, 0]


exp_values = np.exp(sepal_length)

softmax = exp_values / np.sum(exp_values)

print(softmax)

[0.00221959 0.00181724 0.00148783 0.00134625 0.00200836 0.00299613
 0.00134625 0.00200836 0.00110221 0.00181724 0.00299613 0.00164431
 0.00164431 0.00099732 0.0044697  0.00404435 0.00299613 0.00221959
 0.00404435 0.00221959 0.00299613 0.00221959 0.00134625 0.00221959
 0.00164431 0.00200836 0.00200836 0.00245302 0.00245302 0.00148783
 0.00164431 0.00299613 0.00245302 0.00331123 0.00181724 0.00200836
 0.00331123 0.00181724 0.00110221 0.00221959 0.00200836 0.00121813
 0.00110221 0.00200836 0.00221959 0.00164431 0.00221959 0.00134625
 0.00271101 0.00200836 0.01483991 0.00814432 0.01342771 0.00331123
 0.00900086 0.00404435 0.00736928 0.00181724 0.00994749 0.00245302
 0.00200836 0.00493978 0.0054593  0.00603346 0.00365948 0.01099368
 0.00365948 0.0044697  0.006668   0.00365948 0.00493978 0.00603346
 0.00736928 0.00603346 0.00814432 0.00994749 0.01214989 0.01099368
 0.0054593  0.00404435 0.00331123 0.00331123 0.0044697  0.0054593
 0.00299613 0.0054593  0.01099368 0.00736928 0.00365948 0.00331

### Exercise 31 — Percentile Scores

**Question:** Find the 5th and 95th percentile of iris's sepal length.

*# Make sure you have run Exercise 27 first.*


In [77]:
# Write your code here:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv"

iris_data = pd.read_csv(url, header=None)

iris_2d = iris_data.iloc[:, :4].to_numpy()

sepal_length = iris_2d[:, 0]

p5 = np.percentile(sepal_length, 5)
p95 = np.percentile(sepal_length, 95)

print("5th Percentile:", p5)
print("95th Percentile:", p95)

5th Percentile: 4.6
95th Percentile: 7.254999999999998


### Exercise 32 — Insert Missing Values

**Question:** Insert `np.nan` values at 20 random positions in `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [78]:
# Write your code here:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv"

iris_data = pd.read_csv(url, header=None)

iris_2d = iris_data.iloc[:, :4].to_numpy()

rows, cols = iris_2d.shape

for _ in range(20):
    i = np.random.randint(0, rows)
    j = np.random.randint(0, cols)
    iris_2d[i, j] = np.nan

print(iris_2d)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 nan]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [nan 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 nan]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 nan]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

### Exercise 33 — Find Missing Values

**Question:** Find the **number** and **position** of missing values in `iris_2d`'s sepal length (1st column).

*# Make sure you have run Exercise 32 first.*


In [79]:
# Write your code here:

sepal_length = iris_2d[:, 0]


missing_positions = np.where(np.isnan(sepal_length))


missing_count = np.sum(np.isnan(sepal_length))

print("Number of missing values:", missing_count)
print("Positions of missing values:", missing_positions)

Number of missing values: 5
Positions of missing values: (array([ 27,  58, 100, 107, 108]),)


### Exercise 34 — Multi-Condition Filter

**Question:** Filter the rows of `iris_2d` that have:
- petal length (3rd column) > 1.5, **and**
- sepal length (1st column) < 5.0

*# Make sure you have run Exercise 32 first.*


In [80]:
# Write your code here:
import pandas as pd
import numpy as np


url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv"

iris_data = pd.read_csv(url, header=None)


iris_2d = iris_data.iloc[:, :4].to_numpy()

rows, cols = iris_2d.shape

for _ in range(20):
    i = np.random.randint(0, rows)
    j = np.random.randint(0, cols)
    iris_2d[i, j] = np.nan

filtered_rows = iris_2d[
    (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
]

print(filtered_rows)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 nan 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 nan]]


### Exercise 35 — Drop Rows with NaN

**Question:** Select rows of `iris_2d` that do **not** have any `nan` value.

*# Make sure you have run Exercise 32 first.*


In [81]:
# Write your code here:
import pandas as pd
import numpy as np


url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv"

iris_data = pd.read_csv(url, header=None)

iris_2d = iris_data.iloc[:, :4].to_numpy()


rows, cols = iris_2d.shape

for _ in range(20):
    i = np.random.randint(0, rows)
    j = np.random.randint(0, cols)
    iris_2d[i, j] = np.nan


clean_rows = iris_2d[~np.isnan(iris_2d).any(axis=1)]

print(clean_rows)

[[4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [5.  3.4 1.5 0.2]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.

### Exercise 36 — Correlation

**Question:** Find the correlation between sepal length (1st column) and petal length (3rd column) in `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [82]:
# Write your code here:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv"

iris_data = pd.read_csv(url, header=None)

iris_2d = iris_data.iloc[:, :4].to_numpy()

sepal_length = iris_2d[:, 0]
petal_length = iris_2d[:, 2]

correlation = np.corrcoef(sepal_length, petal_length)

print(correlation)

[[1.         0.87175416]
 [0.87175416 1.        ]]


### Exercise 37 — Check for NaN

**Question:** Find out if `iris_2d` has any missing values.

*# Make sure you have run Exercise 32 first.*


In [83]:
# Write your code here:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv"

iris_data = pd.read_csv(url, header=None)

iris_2d = iris_data.iloc[:, :4].to_numpy()

rows, cols = iris_2d.shape

for _ in range(20):
    i = np.random.randint(0, rows)
    j = np.random.randint(0, cols)
    iris_2d[i, j] = np.nan

has_nan = np.isnan(iris_2d).any()

print(has_nan)

True


### Exercise 38 — Replace NaN with 0

**Question:** Replace all occurrences of `nan` with `0` in `iris_2d`.

*# Make sure you have run Exercise 32 first.*


In [84]:
# Write your code here:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv"

iris_data = pd.read_csv(url, header=None)

iris_2d = iris_data.iloc[:, :4].to_numpy()

rows, cols = iris_2d.shape

for _ in range(20):
    i = np.random.randint(0, rows)
    j = np.random.randint(0, cols)
    iris_2d[i, j] = np.nan

iris_2d[np.isnan(iris_2d)] = 0

print(iris_2d)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 0.  0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0. ]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0. ]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [0.  3.1 1.5 0.1]
 [0.  3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 0.  1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

### Exercise 39 — Unique Value Counts

**Question:** Find the unique values and their counts in iris's species column.

*# Make sure you have run Exercise 25 first.*


In [85]:
# Write your code here:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv"

iris_data = pd.read_csv(url, header=None)

species = iris_data[4]

unique_values, counts = np.unique(species, return_counts=True)

print("Unique Values:", unique_values)
print("Counts:", counts)

Unique Values: ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']
Counts: [50 50 50]


### Exercise 40 — Numeric to Categorical

**Question:** Bin the petal length (3rd column) of `iris_2d` to form a text array using these rules:
- `< 3` → `'small'`
- `3–5` → `'medium'`
- `>= 5` → `'large'`

*# Make sure you have run Exercise 27 first.*


In [86]:
# Write your code here:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv"

iris_data = pd.read_csv(url, header=None)


iris_2d = iris_data.iloc[:, :4].to_numpy()

petal_length = iris_2d[:, 2]

categories = np.where(
    petal_length < 3,
    'small',
    np.where(petal_length < 5, 'medium', 'large')
)

print(categories)

['small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'large' 'medium' 'medium' 'medium' 'medium' 'medium' 'large' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'large'
 'large' 'large' 'large' 'large' 'large' 'medium' 'large' 'large' 'large'
 'large' 'large' 'large' 'large' 'large' 'large' 'large' '

### Exercise 41 — Create New Column

**Question:** Create a new column for **volume** in `iris_2d`, where:

> volume = (π × petal_length × sepal_length²) / 3

*# Make sure you have run Exercise 27 first.*


In [87]:
# Write your code here:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv"

iris_data = pd.read_csv(url, header=None)

iris_2d = iris_data.iloc[:, :4].to_numpy()

sepal_length = iris_2d[:, 0]
petal_length = iris_2d[:, 2]

volume = (np.pi * petal_length * (sepal_length ** 2)) / 3

iris_2d = np.column_stack((iris_2d, volume))

print(iris_2d)

[[  5.1          3.5          1.4          0.2         38.13265163]
 [  4.9          3.           1.4          0.2         35.20049849]
 [  4.7          3.2          1.3          0.2         30.07237208]
 [  4.6          3.1          1.5          0.2         33.23805027]
 [  5.           3.6          1.4          0.2         36.65191429]
 [  5.4          3.9          1.7          0.4         51.91167701]
 [  4.6          3.4          1.4          0.3         31.02218026]
 [  5.           3.4          1.5          0.2         39.26990817]
 [  4.4          2.9          1.4          0.2         28.38324243]
 [  4.9          3.1          1.5          0.1         37.71481981]
 [  5.4          3.7          1.5          0.2         45.80442089]
 [  4.8          3.4          1.6          0.2         38.60389053]
 [  4.8          3.           1.4          0.1         33.77840421]
 [  4.3          3.           1.1          0.1         21.29895099]
 [  5.8          4.           1.2          0.2  

### Exercise 42 — Probabilistic Sampling

**Question:** Randomly sample iris's species such that **setosa** appears **twice** as often as versicolor and virginica.

*# Make sure you have run Exercise 25 first.*


In [88]:
# Write your code here:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv"

iris_data = pd.read_csv(url, header=None)
species = iris_data[4].unique()

sampled_species = np.random.choice(
    species,
    size=20,
    p=[0.5, 0.25, 0.25]
)

print(sampled_species)

['Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa' 'Iris-setosa']


### Exercise 43 — Second Largest Value

**Question:** Find the **second longest** petal length among iris samples of species **setosa**.

*# Make sure you have run Exercise 25 first.*


In [89]:
# Write your code here:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv"

iris_data = pd.read_csv(url, header=None)

setosa = iris_data[iris_data[4] == 'Iris-setosa']


petal_length = setosa[2].to_numpy()


second_largest = np.unique(petal_length)[-2]

print("Second longest petal length:", second_largest)

Second longest petal length: 1.7


### Exercise 44 — Sort 2D Array by Column

**Question:** Sort the iris dataset based on the sepal length column.

*# Make sure you have run Exercise 27 first.*


In [90]:
# Write your code here:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv"

iris_data = pd.read_csv(url, header=None)

iris_2d = iris_data.iloc[:, :4].to_numpy()

sorted_iris = iris_2d[iris_2d[:, 0].argsort()]

print(sorted_iris)

[[4.3 3.  1.1 0.1]
 [4.4 2.9 1.4 0.2]
 [4.4 3.2 1.3 0.2]
 [4.4 3.  1.3 0.2]
 [4.5 2.3 1.3 0.3]
 [4.6 3.6 1.  0.2]
 [4.6 3.1 1.5 0.2]
 [4.6 3.4 1.4 0.3]
 [4.6 3.2 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.  1.4 0.3]
 [4.8 3.1 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.9 2.4 3.3 1. ]
 [4.9 3.1 1.5 0.1]
 [4.9 3.1 1.5 0.1]
 [4.9 3.  1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [4.9 2.5 4.5 1.7]
 [5.  3.5 1.3 0.3]
 [5.  3.3 1.4 0.2]
 [5.  3.4 1.6 0.4]
 [5.  3.4 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.  2.  3.5 1. ]
 [5.  3.2 1.2 0.2]
 [5.  3.  1.6 0.2]
 [5.  2.3 3.3 1. ]
 [5.  3.5 1.6 0.6]
 [5.1 3.5 1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [5.1 3.3 1.7 0.5]
 [5.1 3.5 1.4 0.2]
 [5.1 3.8 1.9 0.4]
 [5.1 3.4 1.5 0.2]
 [5.1 3.7 1.5 0.4]
 [5.1 3.8 1.5 0.3]
 [5.1 2.5 3.  1.1]
 [5.2 3.5 1.5 0.2]
 [5.2 4.1 1.5 0.1]
 [5.2 2.7 3.9 1.4]
 [5.2 3.4 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.4 3.9 1.7 0.4]
 [5.4 3.4 1.5 0.4]
 [5.4 3.  4.5 1.5]
 [5.4 3.7 1.5 0.2]
 [5.4 3.4 1.7 0.2]
 [5.4 3.9 1.3 0.4]
 [5.5 4.2 1.

### Exercise 45 — Most Frequent Value

**Question:** Find the most frequent value of petal length (3rd column) in the iris dataset.

*# Make sure you have run Exercise 27 first.*


In [91]:
# Write your code here:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv"

iris_data = pd.read_csv(url, header=None)

iris_2d = iris_data.iloc[:, :4].to_numpy()

petal_length = iris_2d[:, 2]

values, counts = np.unique(petal_length, return_counts=True)


most_frequent = values[np.argmax(counts)]

print("Most frequent petal length:", most_frequent)

Most frequent petal length: 1.5


### Exercise 46 — First Value Greater Than

**Question:** Find the position of the **first occurrence** of a value greater than 1.0 in the petal width (4th column) of `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [92]:
# Write your code here:
import pandas as pd
import numpy as np


url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv"

iris_data = pd.read_csv(url, header=None)

iris_2d = iris_data.iloc[:, :4].to_numpy()

petal_width = iris_2d[:, 3]
position = np.where(petal_width > 1.0)[0][0]

print("Position:", position)

Position: 50


## Section 5 — Miscellaneous (Exercises 47–50)

### Exercise 47 — Clip Values

**Question:** From array `a`, replace all values **greater than 30** with `30`, and all values **less than 10** with `10`.


In [93]:
# Input — do not modify
np.random.seed(100)
a = np.random.uniform(1, 50, 20)

In [94]:
# Write your code here:
import numpy as np
np.random.seed(100)
a = np.random.uniform(1, 50, 20)
a[a>30] = 30
a[a<10]=10
print(a)

[27.62684215 14.64009987 21.80136195 30.         10.         10.
 30.         30.         10.         29.17957314 30.         11.25090398
 10.08108276 10.         11.76517714 30.         30.         10.
 30.         14.42961361]


### Exercise 48 — Top N Positions

**Question:** Get the positions of the **top 5 maximum values** in array `a`.


In [95]:
# Input — do not modify
np.random.seed(100)
a = np.random.uniform(1, 50, 20)

In [96]:
# Write your code here:
import numpy as np

np.random.seed(100)
a = np.random.uniform(1, 50, 20)

top5_positions = np.argsort(a)[-5:]

print(top5_positions)

[18  7  3 10 15]


### Exercise 49 — Row-wise Unique Counts

**Question:** Compute the counts of unique values **row-wise** in the input array.


In [97]:
# Input — do not modify
np.random.seed(100)
arr = np.random.randint(1, 11, size=(6, 10))

In [98]:
# Write your code here:
import numpy as np

arr = np.array([
    [1, 2, 2, 3],
    [4, 4, 4, 4],
    [5, 6, 5, 6]
])

unique_counts = [len(np.unique(row)) for row in arr]

print(unique_counts)

[3, 1, 2]


### Exercise 50 — Flatten Array of Arrays

**Question:** Convert `arr_2d` (an array of arrays) into a flat 1D array.


In [99]:
# Input — do not modify
arr1 = np.arange(3)
arr2 = np.arange(3, 7)
arr3 = np.arange(7, 10)
arr_2d = np.array([arr1, arr2, arr3], dtype=object)

In [100]:
# Write your code here:
import numpy as np

arr1 = np.arange(3)
arr2 = np.arange(3, 7)
arr3 = np.arange(7, 10)

arr_2d = np.array([arr1, arr2, arr3], dtype=object)

flat_array = np.concatenate(arr_2d)

print(flat_array)

[0 1 2 3 4 5 6 7 8 9]


---

## 🎉 Well done!

You've completed all 50 exercises. Review any exercises you found tricky and revisit the NumPy documentation for deeper understanding.